inputs:
  - name: src
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: 3.9.4
run:
  path: sh
  args:
    - -exc
    - |
      apk add --no-cache bash curl
      ./src/scripts/smoke-test.sh
