resources:
  - name: src
    type: git
    source:
      uri: https://github.com/mamachanko/piet
  - name: release
    type: s3
    source:
      bucket: piet
      regexp: "(.*).tar.gz"
      access_key_id: {{minio-access-key}}
      secret_access_key: {{minio-secret-key}}
      endpoint: http://minio:9000
  - name: deployment
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}
  - name: every-5-mins
    type: time
    source:
      interval: 5m
      location: Europe/Berlin
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]
      start: 8:00 AM
      stop: 6:00 PM

jobs:
  - name: build
    plan:
      - get: src
        trigger: true
      - task: build
        config:
          inputs:
            - name: src
          outputs:
            - name: out
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openjdk
              tag: 11
          caches:
            - path: gradle
          params:
            GRADLE_USER_HOME: ../gradle
          run:
            path: src/scripts/build.sh
      - put: release
        params:
          file: out/*.tar.gz
  - name: deploy
    plan:
      - get: release
        trigger: true
        params:
          unpack: true
      - put: deployment
        params:
          manifest: release/manifest.yml
          path: release/piet.jar
          current_app_name: piet
          show_app_log: true
      - get: src
        trigger: false
      - task: smoke-test
        file: src/ci/tasks/smoke-test.yml
        params:
          PIET_BASEURI: https://piet.cfapps.io
  - name: smoke-test
    plan:
      - get: every-5-mins
        trigger: true
      - get: src
        trigger: false
      - task: smoke-test
        file: src/ci/tasks/smoke-test.yml
        params:
          PIET_BASEURI: https://piet.cfapps.io
