resources:
  - name: src
    type: git
    source:
      uri: https://github.com/mamachanko/piet
  - name: release
    type: s3
    source:
      bucket: piet
      regexp: piet-(.*).jar
      access_key_id: {{minio-access-key}}
      secret_access_key: {{minio-secret-key}}
      endpoint: http://minio:9000
  - name: deployment
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}

jobs:
  - name: build
    plan:
      - get: src
        trigger: true
      - task: build
        config:
          inputs:
            - name: src
          outputs:
            - name: out
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openjdk
              tag: 11
          caches:
            - path: gradle
          params:
            GRADLE_USER_HOME: ../gradle
          run:
            path: src/scripts/build.sh
      - put: release
        params:
          file: out/piet-*.jar
  - name: deploy
    plan:
      - get: release
        trigger: true
      - get: src
        trigger: false
      - put: deployment
        params:
          manifest: src/ci/manifest.yml
          path: release/piet-0.0.1-SNAPSHOT.jar
          current_app_name: piet
          show_app_log: true
